New test setup
Sensirion/embedded-sts pull request #21
Opened 2020-09-22 13:01 UTC by Zifzaf

Check the following:

 - [ ] Breaking changes marked in commit message
 - [na] Changelog updated
 - [ ] Code style cleaned (ran `make style-fix`)
 - [ ] Tested on actual hardware

2020-09-22 14:13 UTC, rnestler approved these changes

2020-09-23 07:00 UTC, abrauchli requested changes

2020-09-23 07:00 UTC, abrauchli commented on tests/sts-test.cpp
> +        CHECK_EQUAL_TEXT(0, ret, "sensirion_i2c_mux_select_TEXT(0x72, 0)");
`_TEXT`? 

```suggestion
        CHECK_EQUAL_TEXT(0, ret, "sensirion_i2c_mux_set_single_channel(0x72, 0)");
```

2020-09-23 09:22 UTC, rnestler commented on tests/sts-test.cpp
> +                         "sensirion_i2c_mux_set_single_channel(0x72, 0)");
That doesn't really belong to this commit but should be a fixup of the previous one.

2020-09-23 11:41 UTC, rnestler approved these changes
I squashed some fix-up commits and rewrote some commit messages to give more context.

2020-09-23 13:22 UTC, merged